# Default MQTT listener (TCP)
listener 1883 0.0.0.0
allow_anonymous true

# WebSockets listener (for web browser clients & debugging)
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true

# Persistence settings
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
